version: '3.2'
services:
  db:
    image: postgres:latest
    container_name: flask_db
    restart: always
    environment:
      POSTGRES_USER: 'dev' # DBのユーザー名（＝DB名）
      POSTGRES_PASSWORD: 'pass' # DBのパスワード
    volumes:
      - ./init_db:/docker-entrypoint-initdb.d # TBL定義
      - /tmp/postgresql-data:/var/lib/postgresql/data:z # データ永続化(ホストマウント)
  flask:
    build: .
    container_name: flask_dev
    restart: always
    volumes:
      - ../app:/usr/local/src/work
    ports:
      - 5000:5000
    tty: true
    depends_on:
      - db
    working_dir: /usr/local/src/work # cdと同等
    command: python app.py